### ISSUE TITLE
Замечания по Product Vision и User Stories

### ISSUE THREAD

**Issue by nvamelichev** [ilya2204/flash-cards#1]
- Product Vision:
    - Из трёх предложений в начале, почти копирующих друг друга с разной интонацией, получается что-то вроде змеи, кусающей себя за хвост (ну или циклического линейного списка):
        > Проект flash-cards предзназначен для людей, **изучающих что-то новое**.... Flash-cards предлагает эффективный метод **запомнинания чего-нибудь нового**, используя методику флеш карточек. Таким образом мы решим проблему **запоминания новой информации**, что сильно поможет людям в **изучении чего-либо нового**.

       Давайте попытаемся распутать запутанное:

        - Проект предназначен для людей, "изучающих что-то новое". Но это слишком широкая категория, как мне кажется, в неё входят примерно все от 5 до 105, кто ещё не впал в маразм :-D. Я бы пользователей разделил по ожидаемой активности в приложении: студенты/школьники при подготовке к экзаменам будут использовать его каждый день; люди,  занимающиеся саморазвитием, зайдут пару раз в неделю; а ещё точно будут те, кто "просто посмотрит, услышал про интересный проект".
        - Проект предлагает "эффективный метод запоминания", использующий "методику", суть которой не расшифрована. Да, я-то знаю, что такое флэш-карточки, но читающий ваше вИдение проекта это знать не обязан. Расскажите буквально одним предложением, что будет происходить.
        - Проблему собственно "запоминания новой информации" решает человеческая память. Ваш же проект, скорее всего, поможет **эффективнее** запоминать новое и **быстрее вспоминать** уже запомненное.

    - > исходя из эффективных **научно подтвержденных методик** изучения.
    
        Каких именно методик? В User Stories заглянул, вижу упоминание **интервальных повторений**, его бы в Vision переместить :-)

    - Список рисков мне понравился. Просто и честно :+1: 

- User Stories:
    - Тут три истории, упакованных в один абзац. Пожалуйста, распакуйте их в три отдельные истории :-)
    - Желательно в историях заюзать те классы пользователей, которые вы ранее определили в Vision. Например, "как студент, готовящийся к экзаменам, я хочу ... для того чтобы ...".

**Comment by nvamelichev** [comment]
@mirabu2801 @ilya2204 ^^^

**Comment by ilya2204** [comment]
User Stories и Product Vision поправили
