### ISSUE TITLE
ОО-проектирование готово к проверке

### ISSUE THREAD

**Issue by ilya2204** [ilya2204/flash-cards#2]

**Comment by nvamelichev** [comment]
**По [CRC-карточкам](https://github.com/ilya2204/flash-cards/blob/main/CRC.md):**
* **CardLibrary** "...хранит флэш карточки, реализует методы для CRUD по карточкам" и **SolutionLibrary**
"...хранит решения пользователя по карточкам". 
    * Я бы превратил *Library-классы в "репозитории" в терминологии DDD (Domain-Driven Design): оставил бы в них минимум CRUD-логики (по крайней мере, в публичных методах) и реализовал бы в них методы бизнес-логики, т.е., реальную работу с данными предметной области. 
Например, поиск карточек, удовлетворяющих вашим требованиям или, лучше, какому-то конкретному требованию - это метод бизнес-логики. А вот юзать типичный CRUD-метод "получить все карточки" + фильтровать их каждый раз там, где это потребуется - хуже. Чем больше мест в коде, где нужно отфильтровать карточки по типовому критерию - тем больше шанс ошибиться.
    * Подумайте, не нужен ли вам дополнительный уровень абстракции - например, чтобы на продакшене классы *Library читали данные из файлов, а в юнит-тестах - из коллекций в памяти?
* **InputAnalyzer** "...анализирует ответ пользователя на конкретную карточку, создает новое Solution в SolutionLibrary и возвращает сообщение с отчетом."
    * В текущей формулировке, InputAnalyzer делает много дел одновременно. Он и анализирует ответ (видимо, это основная функциональность), и работает с решениями в библиотеке, и генерирует сообщение с отчётом. 
Предлагаю разделить эту ответственность на несколько классов, а InputAnalyzer будет объединять результаты их работы. Т.е., применить:
        * паттерн "Фасад" (InputAnalyzer)
        * паттерн "Стратегия" - выделить стратегию выполнения действия или вычисления в отдельный класс/лямбда-функцию:
            * сделать отдельный класс для анализа ответа (или лямбда-функцию - ведь анализ ответа это чистое вычисление без побочных эффектов);
            * сделать отдельный класс для генерации отчёта по результатам анализа ответа (или лямбда-функцию!);
            * логику по созданию Solution и его правильному сохранению **можно** оставить "как есть" - наверняка она уже использует класс SolutionLibrary. А можно эту логику перенести в собственно SolutionLibrary: тогда это будет полноценный "репозиторий" в терминологии DDD, обеспечивающий изменение сущностей предметной области в соответствии с бизнес-логикой, а не просто тупой CRUD :-)

UML-диаграммы посмотрю после того, как мы утрясём всё с CRC-карточками. После изменений CRC-карточек не забудьте обновить UML-диаграммы: набор классов и взаимодействия между ними могут существенно измениться!

**Comment by mirabu2801** [comment]
@nvamelichev поправили

**Comment by nvamelichev** [comment]
Отлично! **Первая итерация ОО-дизайна принята, пишите код! :+1:**
@mirabu2801 @ilya2204

**Comment by nvamelichev** [comment]
Эту Issue можно закрывать :-)
@ilya2204 @mirabu2801 ^^^
